### ISSUE TITLE
Json compatibility 

### ISSUE THREAD

**Issue by ModProg** [khonsulabs/rsn#15]
Rsn is kindof a superset of json.

Not sure what the differences in encoding and string escaping are. But maybe we could have a json compatibility Output mode.

**Comment by ecton** [comment]
Unfortunately string escaping is completely incompatible. JSON Unicode escapes, for example, are actually UTF16 code points, causing all sorts of fun with surrogate pairs which we currently can avoid.

Additionally, it would require a different way of encoding enums, one of the main reasons to me for using Ron/rsn. 

I'm not sure how we could make this work without specifically complicating Rsn for this purpose.

**Comment by ModProg** [comment]
Well it would be lossy, dropping both struct and enum names. But yeah the string escaping would be a problem. And probably, if you want json use json.
