### ISSUE TITLE
Add support for indexmap

### ISSUE THREAD

**Issue by hardliner66** [khonsulabs/rsn#19]
It would be nice if rsn supported indexmap (through a feature flag) so it can be used for serializing when field order matters.

**Comment by ecton** [comment]
Is there anything in particular you feel like this crate needs to do? `indexmap` supports all serde serialization formats by enabling the optional `serde`  feature in its crate. The `Value` type in this crate already treats maps as ordered-preserved, key-value pairs by returning them in a Vec.

**Comment by hardliner66** [comment]
Apparently not. I'm so used to having to enable the `indexmap` feature in serde-json and toml, that I simply overlooked the fact that it already works out of the box. Sorry for the inconvenience.
