### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by dVeon-loch** [khonsulabs/rsn#21]
Is this project still maintained? Can we expect a "stable release" at some point?

**Comment by ecton** [comment]
As far as I know, this project is stable and ready to be used and bug free. However, I have yet to personally extensively enough for me to be confident that we haven't missed some interesting serde serialization patterns that other people want to use with this library.

The download graphs on crates.io also don't really show much adoption yet.

So let's flip this issue around: If you are using Rsn in a project, leave a thumbs up on this comment. Once we have more than a few reactions without bug reports that require breaking changes to fix, we'll release a 1.0.

Thank you for asking!

**Comment by ecton** [comment]
We've released [v0.2.0](https://github.com/khonsulabs/rsn/releases/tag/v0.2.0) with some bug fixes an updates.
